In [1]:
import numpy as np
import pandas as pd

# Small part of Feed Grains: Yearbook Tables
# Data used from https://www.ers.usda.gov/data-products/feed-grains-database/feed-grains-yearbook-tables/
# Price per bushel of Yellow corn in 1984, 1985
# Array will be used when applicable for examples.
df = pd.read_csv('FeedGrains.csv')
cornArray = df['Amount'].to_numpy().astype(np.float64).reshape(2,13) #Reshape


# Understanding Data Types in Python

Topics covered Include:
1. Creating an array from a python list
2. Creating an array from scratch

In [2]:
# Creating an Array From a Python List
lyst = [1, 2, 3, 4, 5]
arr = np.array(lyst, dtype = np.int32)
print(arr)

[1 2 3 4 5]


In [3]:
# Creating an Array From Scratch
arr = np.zeros(5)                       # Using zeros
print(arr)

arr = np.random.randint(20, 40, (2, 3)) # Using random
print(arr)

[0. 0. 0. 0. 0.]
[[23 36 29]
 [21 21 24]]


# The Basics of NumPy Arrays

Topics covered Include:
1. Attributes of Arrays
2. Array Indexing & Slicing
3. Concatenation

In [4]:
# Attributes of Arrays

print("Corn Array Number of Dimensions: ", cornArray.ndim)      # 2
print("Corn Array Shape:                ", cornArray.shape)     # (2, 13)
print("Corn Array Size:                 ", cornArray.size)      # 26
print("Corn Array Data Type:            ", cornArray.dtype)     # Float 64
print("Corn Array Item Size:            ", cornArray.itemsize)  # 8
print("Corn Array Array Size in Bytes:  ", cornArray.nbytes)    # 208

Corn Array Number of Dimensions:  2
Corn Array Shape:                 (2, 13)
Corn Array Size:                  26
Corn Array Data Type:             float64
Corn Array Item Size:             8
Corn Array Array Size in Bytes:   208


In [5]:
# Array Indexing & Slicing

# Sep-Aug Avg.
print("Corn Price Average:                      ", cornArray[0,12])     # Single Value
print("All Corn Prices for Year 1984:           ", cornArray[0,:12])    # All Corn Prices for Year 1984
print("March - June Corn Prices for Year 1986:  ", cornArray[1,2:6])    # March - June Corn Prices for Year 1986

Corn Price Average:                       3.08833333333333
All Corn Prices for Year 1984:            [3.54 3.63 3.84 3.91 3.73 3.94 3.76 3.58 3.34 3.04 2.92 3.  ]
March - June Corn Prices for Year 1986:   [3.13 3.2  3.1  3.25]


In [6]:
#Concatenation

x = np.array([1, 2, 3, 3, 2, 1]).reshape(2,3)
y = np.array([3, 2, 1, 1, 2, 3]).reshape(2,3)
print(np.concatenate([x, y]))

[[1 2 3]
 [3 2 1]
 [3 2 1]
 [1 2 3]]


# Universal Functions

Topics covered Include:
1. Array Arithmetic
2. Equivalent Functions
3. Exponents and Logarithms

In [7]:
# Array Arithmetic

print(cornArray[0,::]) # Original
print('Array + 4:', cornArray[0,::] + 4)
print('Array - 4:', cornArray[0,::] - 4)
print('Array * 4:', cornArray[0,::] * 4)
print('Array / 4:', cornArray[0,::] / 4)
print('Array // 2:', cornArray[0,::] // 2)
print('-Array:', -cornArray[0,::])
print('Array ^ 2:', cornArray[0,::] ** 2)
print('Array % 2:', cornArray[0,::] % 2)

[3.54       3.63       3.84       3.91       3.73       3.94
 3.76       3.58       3.34       3.04       2.92       3.
 3.08833333]
Array + 4: [7.54       7.63       7.84       7.91       7.73       7.94
 7.76       7.58       7.34       7.04       6.92       7.
 7.08833333]
Array - 4: [-0.46       -0.37       -0.16       -0.09       -0.27       -0.06
 -0.24       -0.42       -0.66       -0.96       -1.08       -1.
 -0.91166667]
Array * 4: [14.16       14.52       15.36       15.64       14.92       15.76
 15.04       14.32       13.36       12.16       11.68       12.
 12.35333333]
Array / 4: [0.885      0.9075     0.96       0.9775     0.9325     0.985
 0.94       0.895      0.835      0.76       0.73       0.75
 0.77208333]
Array // 2: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
-Array: [-3.54       -3.63       -3.84       -3.91       -3.73       -3.94
 -3.76       -3.58       -3.34       -3.04       -2.92       -3.
 -3.08833333]
Array ^ 2: [12.5316     13.1769     14.7456     15.2881

In [8]:
# Equivalent Functions

print('Array + 4:', cornArray[0,::] + 4)
print('Array + 4:', np.add(cornArray[0,::], 4))

Array + 4: [7.54       7.63       7.84       7.91       7.73       7.94
 7.76       7.58       7.34       7.04       6.92       7.
 7.08833333]
Array + 4: [7.54       7.63       7.84       7.91       7.73       7.94
 7.76       7.58       7.34       7.04       6.92       7.
 7.08833333]


In [9]:
# Exponents and Logarithms

print('Array:', cornArray[0,::])
print('e ^ Array:', np.exp(cornArray[0,::]))
print('log2 of Array:', np.log2(cornArray[0,::]))

Array: [3.54       3.63       3.84       3.91       3.73       3.94
 3.76       3.58       3.34       3.04       2.92       3.
 3.08833333]
e ^ Array: [34.46691919 37.71281662 46.52547444 49.89895197 41.67910816 51.4186013
 42.94842598 35.87354085 28.21912671 20.90524324 18.54128746 20.08553692
 21.94048002]
log2 of Array: [1.82374936 1.85996955 1.94110631 1.96716861 1.89917563 1.97819563
 1.91073266 1.83995959 1.7398481  1.60407132 1.54596837 1.5849625
 1.62682848]


# Aggregations

1. Summations
2. Min and Max
3. Other

In [10]:
# Summations

print(cornArray)
print(sum(cornArray))       # Built in Python sum
print(np.sum(cornArray))    # numpy's Sum

[[3.54       3.63       3.84       3.91       3.73       3.94
  3.76       3.58       3.34       3.04       2.92       3.
  3.08833333]
 [3.1        3.08       3.13       3.2        3.1        3.25
  3.1        2.8        2.5        2.45       2.7        2.85
  2.65      ]]
[6.64       6.71       6.97       7.11       6.83       7.19
 6.86       6.38       5.84       5.49       5.62       5.85
 5.73833333]
83.22833333333332


In [11]:
# Min and Max

print('Array:', cornArray[0,:6:])

print('Python Min', min(cornArray[0,:6:]))
print('numpy Min', np.min(cornArray[0,:6:]))

print('Python Max', max(cornArray[0,:6:]))
print('numpy Max', np.max(cornArray[0,:6:]))

Array: [3.54 3.63 3.84 3.91 3.73 3.94]
Python Min 3.54
numpy Min 3.54
Python Max 3.94
numpy Max 3.94


In [12]:
# Other

print('Array:', cornArray)
print('Array:', np.std(cornArray))      # Standard Deviation
print('Array:', np.median(cornArray))   # Median

Array: [[3.54       3.63       3.84       3.91       3.73       3.94
  3.76       3.58       3.34       3.04       2.92       3.
  3.08833333]
 [3.1        3.08       3.13       3.2        3.1        3.25
  3.1        2.8        2.5        2.45       2.7        2.85
  2.65      ]]
Array: 0.4213548919112499
Array: 3.1


# Broadcasting
1. Example 1 - Subtraction Broadcasting
2. Example 2 - Expected Failure
3. Example 3 - Centering of cornArray

In [13]:
# Example 1 - Subtraction Broadcasting

arr1 = np.array([0, 1, 2])
arr2 = np.array([9, 8, 7]).reshape(3,1)
print('Array 1: ', arr1)
print('Array 2: \n',arr2)

print("Subtraction Broadcasting: \n", arr1 - arr2)

Array 1:  [0 1 2]
Array 2: 
 [[9]
 [8]
 [7]]
Subtraction Broadcasting: 
 [[-9 -8 -7]
 [-8 -7 -6]
 [-7 -6 -5]]


In [14]:
# Example 2 - Expected Failure

arr1 = np.array([0, 1, 2])
arr2 = np.array([9, 8, 7, 6]).reshape(2,2)

try:
    print("Addition Broadcasting: \n", arr1 + arr2)
except:
    print("This does not work because the two arrays are not compatible.")

This does not work because the two arrays are not compatible.


In [15]:
# Example 3 - Centering of cornArray

print(cornArray)
print("Array Mean of x axis:\n", cornArray.mean(0))
print("cornArray centered:\n", (cornArray - cornArray.mean(0)).mean(0))


[[3.54       3.63       3.84       3.91       3.73       3.94
  3.76       3.58       3.34       3.04       2.92       3.
  3.08833333]
 [3.1        3.08       3.13       3.2        3.1        3.25
  3.1        2.8        2.5        2.45       2.7        2.85
  2.65      ]]
Array Mean of x axis:
 [3.32       3.355      3.485      3.555      3.415      3.595
 3.43       3.19       2.92       2.745      2.81       2.925
 2.86916667]
cornArray centered:
 [-2.22044605e-16  0.00000000e+00  0.00000000e+00  0.00000000e+00
  0.00000000e+00  2.22044605e-16  2.22044605e-16  0.00000000e+00
  0.00000000e+00  0.00000000e+00  0.00000000e+00  2.22044605e-16
  0.00000000e+00]


# Comparisons, Masks, and Boolean Logic

1. Comparison Operators
2. Boolean Arrays
3. Boolean Arrays as Masks

In [16]:
# Comparison Operators

print(cornArray[0, :6])
print(' Are values greater than 3.75:\n', cornArray[0, :6] > 3.75)
print(' Are values less than 3.8:\n', cornArray[0, :6] < 3.8)


[3.54 3.63 3.84 3.91 3.73 3.94]
 Are values greater than 3.75:
 [False False  True  True False  True]
 Are values less than 3.8:
 [ True  True False False  True False]


In [17]:
# Boolean Arrays

cornBool = cornArray[0, :6] > 3.75  # Count True
print('How many values greater than 3.75:\n', np.count_nonzero(cornBool))



How many values greater than 3.75:
 3


In [18]:
# Boolean Arrays as Masks

smlCornArray = cornArray[0, :6]             # Create Smaller Array
print("All values that satisfy the expression:", 
      smlCornArray[smlCornArray > 3.75])    # Get values that match comparison operation




All values that satisfy the expression: [3.84 3.91 3.94]


# Fancy Indexing
1. Example 1 - Basics
2. Example 2 - Modifying Values

In [19]:
# Example 1 - Basics

# One Dimension Access Array
smlCornArray = cornArray[0, :6]     # Create Smaller Array
accessArray = [1, 3, 5]

print("Array: ", smlCornArray)
print("Indices that will be accessed: ", accessArray)
print("Array: ", smlCornArray[accessArray])
print()

# Two Dimension Access Array
accessArray2 = np.array([[1, 2],
                         [4, 5]])
print("Array: ", smlCornArray)
print("Indices that will be accessed:\n ", accessArray2)
print("Array: \n", smlCornArray[accessArray2])


Array:  [3.54 3.63 3.84 3.91 3.73 3.94]
Indices that will be accessed:  [1, 3, 5]
Array:  [3.63 3.91 3.94]

Array:  [3.54 3.63 3.84 3.91 3.73 3.94]
Indices that will be accessed:
  [[1 2]
 [4 5]]
Array: 
 [[3.63 3.84]
 [3.73 3.94]]


In [20]:
# Example 2 - Modifying Values

accessArray = [1, 3, 5]
temp = np.copy(smlCornArray)

print("Array: ", temp)
print("Indices that will be accessed: ", accessArray)
temp[accessArray] = -99
print("Changed Array: ", temp)
print()


Array:  [3.54 3.63 3.84 3.91 3.73 3.94]
Indices that will be accessed:  [1, 3, 5]
Changed Array:  [  3.54 -99.     3.84 -99.     3.73 -99.  ]



# Sorting Arrays
1. Numpy Sorting

In [21]:
# Numpy Sorting

# np.sort

tempCornArray = np.copy(cornArray[0, :12])   # Create Smaller Array

print('Array:               ', tempCornArray)
print('Sorted with np.sort  ', np.sort(tempCornArray))

Array:                [3.54 3.63 3.84 3.91 3.73 3.94 3.76 3.58 3.34 3.04 2.92 3.  ]
Sorted with np.sort   [2.92 3.   3.04 3.34 3.54 3.58 3.63 3.73 3.76 3.84 3.91 3.94]


In [22]:
# np.argsort

tempCornArray = np.copy(cornArray[0, :12])   # Create Smaller Array
print('Array:                   ', tempCornArray)
print('Sorted with np.argsort   ', np.argsort(tempCornArray))

Array:                    [3.54 3.63 3.84 3.91 3.73 3.94 3.76 3.58 3.34 3.04 2.92 3.  ]
Sorted with np.argsort    [10 11  9  8  0  7  1  4  6  2  3  5]


In [23]:
# Sort rows

tempCornArray = np.copy(cornArray)
print("sorted rows: ", np.sort(tempCornArray, axis = 1))


sorted rows:  [[2.92       3.         3.04       3.08833333 3.34       3.54
  3.58       3.63       3.73       3.76       3.84       3.91
  3.94      ]
 [2.45       2.5        2.65       2.7        2.8        2.85
  3.08       3.1        3.1        3.1        3.13       3.2
  3.25      ]]


# Structured Arrays
1. Structured Arrays

In [24]:
structCornArray = np.zeros(12, dtype={'names':('Month', 'PPB'),
                          'formats':('U20', 'f8')})

structCornArray[0]['Month'] = 'Jan'
structCornArray[1]['Month'] = 'Feb'
structCornArray[2]['Month'] = 'Mar'
structCornArray[3]['Month'] = 'Apr'
structCornArray[4]['Month'] = 'May'
structCornArray[5]['Month'] = 'Jun'
structCornArray[6]['Month'] = 'Jul'
structCornArray[7]['Month'] = 'Aug'
structCornArray[8]['Month'] = 'Sep'
structCornArray[9]['Month'] = 'Oct'
structCornArray[10]['Month'] = 'Nov'
structCornArray[11]['Month'] = 'Dec'

structCornArray[0]['PPB'] = cornArray[0,0]
structCornArray[1]['PPB'] = cornArray[0,1]
structCornArray[2]['PPB'] = cornArray[0,2]
structCornArray[3]['PPB'] = cornArray[0,3]
structCornArray[4]['PPB'] = cornArray[0,4]
structCornArray[5]['PPB'] = cornArray[0,5]
structCornArray[6]['PPB'] = cornArray[0,6]
structCornArray[7]['PPB'] = cornArray[0,7]
structCornArray[8]['PPB'] = cornArray[0,8]
structCornArray[9]['PPB'] = cornArray[0,9]
structCornArray[10]['PPB'] = cornArray[0,10]
structCornArray[11]['PPB'] = cornArray[0,11]

print("This is a Structured Array: \n", structCornArray)
print("This is an Accessing by Index Example:\n", structCornArray[0])
print("This is an Accessing by Field Example:\n", structCornArray['PPB'])
print("This is an Accessing by Conditional Example:\n", structCornArray[structCornArray['PPB'] > 3.5]['Month'])

This is a Structured Array: 
 [('Jan', 3.54) ('Feb', 3.63) ('Mar', 3.84) ('Apr', 3.91) ('May', 3.73)
 ('Jun', 3.94) ('Jul', 3.76) ('Aug', 3.58) ('Sep', 3.34) ('Oct', 3.04)
 ('Nov', 2.92) ('Dec', 3.  )]
This is an Accessing by Index Example:
 ('Jan', 3.54)
This is an Accessing by Field Example:
 [3.54 3.63 3.84 3.91 3.73 3.94 3.76 3.58 3.34 3.04 2.92 3.  ]
This is an Accessing by Conditional Example:
 ['Jan' 'Feb' 'Mar' 'Apr' 'May' 'Jun' 'Jul' 'Aug']
